In [2]:
import pandas as pd
import matplotlib.pyplot as plt

In [38]:
df_2014=pd.read_csv("2014년도_전·출입 및 학업중단 학생 수(고)_전체.csv")
df_2015=pd.read_csv("2015년도_전·출입 및 학업중단 학생 수(고)_전체.csv")
df_2016=pd.read_csv("2016년도_전·출입 및 학업중단 학생 수(고)_전체.csv")
df_2017=pd.read_csv("2017년도_전·출입 및 학업중단 학생 수(고)_전체.csv")
df_2018=pd.read_csv("2018년도_전·출입 및 학업중단 학생 수(고)_전체.csv")
df_2019=pd.read_csv("2019년도_전·출입 및 학업중단 학생 수(고)_전체.csv")
df_2020=pd.read_csv("2020년도_전·출입 및 학업중단 학생 수(고)_전체.csv")
df_2021=pd.read_csv("2021년도_전·출입 및 학업중단 학생 수(고)_전체.csv")
df_2022=pd.read_csv("2022년도_전·출입 및 학업중단 학생 수(고)_전체.csv")
df_2023=pd.read_csv("2023년도_전·출입 및 학업중단 학생 수(고)_전체.csv")

In [12]:
df10

,시도교육청,교육지원청,지역,정보공시 학교코드,학교명,학교급코드,설립구분,제외여부,제외사유,고등부1학년 전입학생수,...,고등부1학년 전체학생수,고등부2학년 전입학생수,고등부2학년 전출학생수,고등부2학년 전체학생수,고등부3학년 전입학생수,고등부3학년 전출학생수,고등부3학년 전체학생수,전입학생수(계),전출학생수(계),전체학생수(계)
0,서울특별시교육청,교육부,서울특별시 강남구,S000003540,국립국악고등학교,4,국립,N,NaN,0.0,...,150.0,0.0,3.0,145.0,0.0,0.0,142.0,0.0,7.0,437.0
1,서울특별시교육청,교육부,서울특별시 성북구,S000003561,서울대학교사범대학부설고등학교,4,국립,N,NaN,12.0,...,226.0,3.0,0.0,223.0,0.0,1.0,228.0,15.0,3.0,677.0
2,서울특별시교육청,교육부,서울특별시 금천구,S000005401,국립전통예술고등학교,4,국립,N,NaN,0.0,...,180.0,0.0,8.0,169.0,0.0,0.0,174.0,0.0,10.0,523.0
3,서울특별시교육청,서울특별시교육청,서울특별시 송파구,S010000370,가락고등학교,4,공립,N,NaN,19.0,...,237.0,7.0,6.0,251.0,0.0,1.0,279.0,26.0,16.0,767.0
4,서울특별시교육청,서울특별시교육청,서울특별시 강동구,S010000371,강동고등학교,4,사립,N,NaN,13.0,...,217.0,8.0,7.0,195.0,1.0,2.0,203.0,22.0,12.0,615.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2416,제주특별자치도교육청,제주특별자치도교육청,제주특별자치도 제주시,S170000157,제주고등학교,4,공립,N,NaN,7.0,...,237.0,6.0,8.0,230.0,0.0,0.0,243.0,13.0,13.0,710.0
2417,제주특별자치도교육청,제주특별자치도교육청,제주특별자치도 서귀포시,S170000158,서귀포산업과학고등학교,4,공립,N,NaN,2.0,...,146.0,1.0,5.0,127.0,1.0,0.0,120.0,4.0,15.0,393.0
2418,제주특별자치도교육청,제주특별자치도교육청,제주특별자치도 서귀포시,S170000159,성산고등학교,4,공립,N,NaN,4.0,...,68.0,3.0,5.0,74.0,2.0,1.0,55.0,9.0,18.0,197.0
2419,제주특별자치도교육청,제주특별자치도교육청,제주특별자치도 제주시,S170000773,제주외국어고등학교,4,공립,N,NaN,2.0,...,101.0,2.0,5.0,93.0,0.0,0.0,87.0,4.0,13.0,281.0
2420,제주특별자치도교육청,제주특별자치도교육청,제주특별자치도 제주시,S170000155,제주제일고등학교부설방송통신고등학교,11,공립,N,NaN,15.0,...,145.0,24.0,4.0,132.0,1.0,0.0,153.0,40.0,11.0,430.0

In [36]:
list[df_2014["고등부1학년 전입학생수"].sum(),
df_2014["고등부1학년 전출학생수"].sum(),
df_2014["고등부1학년 전체학생수"].sum(),
df_2014["고등부2학년 전입학생수"].sum(),
df_2014["고등부2학년 전출학생수"].sum(),
df_2014["고등부2학년 전체학생수"].sum(),
df_2014["고등부3학년 전입학생수"].sum(),
df_2014["고등부3학년 전출학생수"].sum(),
df_2014["고등부3학년 전체학생수"].sum(),
df_2014["전입학생수(계)"].sum(),
df_2014["전출학생수(계)"].sum(),
df_2014["전체학생수(계)"].sum(),]

list[11667.0, 11679.0, 430394.0, 5637.0, 5604.0, 407077.0, 892.0, 737.0, 434184.0, 18196.0, 18020.0, 1271655.0]

In [37]:
list[df_2015["고등부1학년 전입학생수"].sum(),
df_2015["고등부1학년 전출학생수"].sum(),
df_2015["고등부1학년 전체학생수"].sum(),
df_2015["고등부2학년 전입학생수"].sum(),
df_2015["고등부2학년 전출학생수"].sum(),
df_2015["고등부2학년 전체학생수"].sum(),
df_2015["고등부3학년 전입학생수"].sum(),
df_2015["고등부3학년 전출학생수"].sum(),
df_2015["고등부3학년 전체학생수"].sum(),
df_2015["전입학생수(계)"].sum(),
df_2015["전출학생수(계)"].sum(),
df_2015["전체학생수(계)"].sum(),]

list[15744.0, 15979.0, 636701.0, 6923.0, 6986.0, 628724.0, 766.0, 803.0, 636878.0, 23433.0, 23768.0, 1902303.0]